const list = [
  {
    id: 1,
    title: "Türk Kahvesi",
    author: "Kuru kahve çeşitleri arasında bulunan ve kahve çekirdeğinin çok ince olarak çekilip kavrulmasıyla oluşturulan geleneksel bir lezzettir.",
    price: 20,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-2.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Espresso",
    author: "Hemen hemen tüm kahvelerin çıkış noktası espressodan geçer. İnce olarak öğütülmüş olan kahve, makinelerdeki belirli bir basınç ve yüksek sıcaklıktaki suyla bardağa dökülür.",
    price: 15,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-4.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Americano",
    author: "İtalyanlar tarafından geliştirilen bu kahve çeşidi espressoya su eklenmesiyle oluşturulur. Filtre kahveye benzeyen bu lezzetin sertlik derecesini ise Americanoya konan kahve ve su miktarı belirler",
    price: 20,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-5.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Doppio",
    author: "İki shot espresso ile hazırlanan bu kahve Americanoya benzemektedir ancak; Americanoya göre daha sert bir tada sahiptir",
    price: 25,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-6.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Cappuccino",
    author: "Sütlü kahve çeşitleri arasında yer alan bu kahve, espresso ve sütle yapılır. Türkiye’de de sıklıkla tüketilen kahve, soğumaması için porselen fincanlarda servis edilir.",
    price: 15,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-7.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Latte",
    author: "Espresso ile hazırlanan kahve, üç ya da beş ml oranında buharlanmış sütle hazırlanır. Hazır kahve çeşitleri içerisinde de oldukça revaçta olan bir kahvedir.",
    price: 20,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-8.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Mocca ",
    author: "Aromalı kahve çeşitleri içerisinde belki de en kalorili olanı moccadır. Çikolata şurubuyla yapılan kahvenin temelinde espresso bulunur.",
    price: 15,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-12.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Caffe Misto",
    author: "Hafif kahve çeşitleri arasında yerini alan bu lezzet, %50 süt ve %50 filtre kahveden oluşur. Sizler de sabahları kahve içerek güne zinde başlamak isterseniz bu kahveye bir şans verebilirsiniz",
    price: 25,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-15.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Cold Brew",
    author: "Zahmetli bir soğuk demleme ürünüdür. Kahve yaklaşık olarak 12 saatte demlenir. Buzlu su ile servis yapılır.",
    price: 15,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-16.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Sütlü Cold Brew",
    author: "Acı kahve sevmeyenlerin tercih edebileceği bir alternatif olan kahve, zahmetli soğuk demleme sonrasında cold brew içine süt eklenmesiyle oluşturulur.",
    price: 15,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-17.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Eiskaffee",
    author: "Almanların soğuk kahvesidir. İçerisine vanilyalı dondurma, süt ve tatlandırıcı eklenir.",
    price: 20,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-22.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Fas Kahvesi",
    author: "Bu kahve ilk bakışta sütlü Türk kahvesini oldukça andırır. Ancak kahve öğütülürken içerisine susam, muskat ve karabiber konur. Kahve pişirilirken bu karışım ile pişirilir.",
    price: 15,
    img: "https://i.nefisyemektarifleri.com/2017/12/18/kahve-cesitleri-nelerdir-26.jpg",
    amount: 1,
  },
];

export default list;
